### ISSUE TITLE
[Feature request] - Support for immutable?

### ISSUE THREAD

**Issue by Togrias** [erikras/react-final-form#14]
Currently migrating from redux-form;

Are there intentions to support immutable data structure a la redux-form/immutable ?

Thank you!

**Comment by bertho-zero** [comment]
"a la": français spotted ;)

**Comment by erikras** [comment]
There are currently not any intentions, no. The main reason `redux-form` provides that is because many people use `immutable` as their data structure in Redux. I have not thought about it too deeply, but I don't see any immediate advantages to using `immutable` in 🏁 Final Form, but I would be open to hearing arguments in favor of it.
